/**
 * Seed data loaded into localStorage the very first time the app runs.
 * After that, all mutations come from the EmployeeContext CRUD actions.
 */

export const EMPLOYEE_SEED = [
  {
    id:             'emp_001',
    name:           'Sam Wilson',
    email:          's.wilson@company.com',
    phone:          '+1 (555) 101-0001',
    role:           'employee',
    department:     'Engineering',
    jobTitle:       'Senior Software Engineer',
    employmentType: 'Full-time',
    status:         'Active',
    joinDate:       '2022-07-20',
    salary:         95000,
    address:        '12 Maple St, Austin TX',
    emergencyContact: 'Lisa Wilson · +1 (555) 101-0099',
  },
  {
    id:             'emp_002',
    name:           'Jordan Lee',
    email:          'j.lee@company.com',
    phone:          '+1 (555) 102-0002',
    role:           'employee',
    department:     'Design',
    jobTitle:       'UI/UX Designer',
    employmentType: 'Full-time',
    status:         'Inactive',
    joinDate:       '2021-11-05',
    salary:         78000,
    address:        '88 Oak Ave, Seattle WA',
    emergencyContact: 'Chris Lee · +1 (555) 102-0088',
  },
  {
    id:             'emp_003',
    name:           'Casey Nguyen',
    email:          'c.nguyen@company.com',
    phone:          '+1 (555) 103-0003',
    role:           'employee',
    department:     'Marketing',
    jobTitle:       'Marketing Manager',
    employmentType: 'Full-time',
    status:         'Active',
    joinDate:       '2023-01-15',
    salary:         82000,
    address:        '45 Elm Rd, Chicago IL',
    emergencyContact: 'Dana Nguyen · +1 (555) 103-0077',
  },
  {
    id:             'emp_004',
    name:           'Riley Patel',
    email:          'r.patel@company.com',
    phone:          '+1 (555) 104-0004',
    role:           'employee',
    department:     'Finance',
    jobTitle:       'Financial Analyst',
    employmentType: 'Full-time',
    status:         'Active',
    joinDate:       '2020-06-01',
    salary:         88000,
    address:        '7 Pine Blvd, New York NY',
    emergencyContact: 'Priya Patel · +1 (555) 104-0066',
  },
  {
    id:             'emp_005',
    name:           'Taylor Kim',
    email:          't.kim@company.com',
    phone:          '+1 (555) 105-0005',
    role:           'hr',
    department:     'Human Resources',
    jobTitle:       'HR Business Partner',
    employmentType: 'Full-time',
    status:         'Active',
    joinDate:       '2021-03-10',
    salary:         80000,
    address:        '33 Cedar Ln, Portland OR',
    emergencyContact: 'Jamie Kim · +1 (555) 105-0055',
  },
  {
    id:             'emp_006',
    name:           'Morgan Chen',
    email:          'm.chen@company.com',
    phone:          '+1 (555) 106-0006',
    role:           'employee',
    department:     'Engineering',
    jobTitle:       'Backend Engineer',
    employmentType: 'Contract',
    status:         'Active',
    joinDate:       '2023-04-01',
    salary:         90000,
    address:        '21 Birch Ct, San Francisco CA',
    emergencyContact: 'Wei Chen · +1 (555) 106-0044',
  },
  {
    id:             'emp_007',
    name:           'Avery Davis',
    email:          'a.davis@company.com',
    phone:          '+1 (555) 107-0007',
    role:           'employee',
    department:     'Operations',
    jobTitle:       'Operations Lead',
    employmentType: 'Full-time',
    status:         'Active',
    joinDate:       '2019-09-12',
    salary:         75000,
    address:        '99 Walnut St, Denver CO',
    emergencyContact: 'Sam Davis · +1 (555) 107-0033',
  },
  {
    id:             'emp_008',
    name:           'Quinn Martinez',
    email:          'q.martinez@company.com',
    phone:          '+1 (555) 108-0008',
    role:           'employee',
    department:     'Product',
    jobTitle:       'Product Manager',
    employmentType: 'Full-time',
    status:         'Active',
    joinDate:       '2022-02-14',
    salary:         105000,
    address:        '56 Spruce Way, Boston MA',
    emergencyContact: 'Elena Martinez · +1 (555) 108-0022',
  },
  {
    id:             'emp_009',
    name:           'Drew Thompson',
    email:          'd.thompson@company.com',
    phone:          '+1 (555) 109-0009',
    role:           'employee',
    department:     'Legal',
    jobTitle:       'Legal Counsel',
    employmentType: 'Part-time',
    status:         'Active',
    joinDate:       '2020-11-30',
    salary:         120000,
    address:        '14 Aspen Dr, Miami FL',
    emergencyContact: 'Parker Thompson · +1 (555) 109-0011',
  },
  {
    id:             'emp_010',
    name:           'Skyler Brown',
    email:          's.brown@company.com',
    phone:          '+1 (555) 110-0010',
    role:           'employee',
    department:     'Design',
    jobTitle:       'Graphic Designer',
    employmentType: 'Intern',
    status:         'Active',
    joinDate:       '2024-01-08',
    salary:         35000,
    address:        '77 Willow Rd, Nashville TN',
    emergencyContact: 'Alex Brown · +1 (555) 110-0010',
  },
  {
    id:             'emp_011',
    name:           'Maria Garcia',
    email:          'hr@company.com',
    phone:          '+1 (555) 002-0002',
    role:           'hr',
    department:     'Human Resources',
    jobTitle:       'HR Director',
    employmentType: 'Full-time',
    status:         'Active',
    joinDate:       '2021-03-10',
    salary:         110000,
    address:        '5 Rosewood Ct, Los Angeles CA',
    emergencyContact: 'Carlos Garcia · +1 (555) 002-0099',
  },
  {
    id:             'emp_012',
    name:           'Alex Johnson',
    email:          'admin@company.com',
    phone:          '+1 (555) 001-0001',
    role:           'admin',
    department:     'Engineering',
    jobTitle:       'CTO',
    employmentType: 'Full-time',
    status:         'Active',
    joinDate:       '2020-01-15',
    salary:         150000,
    address:        '1 Tech Park, Austin TX',
    emergencyContact: 'Jordan Johnson · +1 (555) 001-0098',
  },
];

export const EMPLOYEES_STORAGE_KEY = 'employees';
