/**
 * Seed data loaded into localStorage the very first time the app runs.
 * After that, all mutations come from the EmployeeContext CRUD actions.
 */

export const EMPLOYEE_SEED = [
  {
    id: 'emp_001',
    name: 'Rahul Verma',
    email: 's.wilson@company.com',
    phone: '+91 98765 43210',
    role: 'employee',
    department: 'Engineering',
    jobTitle: 'Senior Software Engineer',
    employmentType: 'Full-time',
    status: 'Active',
    joinDate: '2022-07-20',
    salary: 95000,
    address: '12 MG Road, Ahmedabad, Gujarat',
    emergencyContact: 'Anita Verma · +91 98765 40001',
  },
  {
    id: 'emp_002',
    name: 'Neha Kapoor',
    email: 'j.lee@company.com',
    phone: '+91 98765 43211',
    role: 'employee',
    department: 'Design',
    jobTitle: 'UI/UX Designer',
    employmentType: 'Full-time',
    status: 'Inactive',
    joinDate: '2021-11-05',
    salary: 78000,
    address: '45 Satellite Road, Ahmedabad, Gujarat',
    emergencyContact: 'Rajesh Kapoor · +91 98765 40002',
  },
  {
    id: 'emp_003',
    name: 'Ananya Iyer',
    email: 'c.nguyen@company.com',
    phone: '+91 98765 43212',
    role: 'employee',
    department: 'Marketing',
    jobTitle: 'Marketing Manager',
    employmentType: 'Full-time',
    status: 'Active',
    joinDate: '2023-01-15',
    salary: 82000,
    address: '18 Anna Nagar, Chennai, Tamil Nadu',
    emergencyContact: 'Suresh Iyer · +91 98765 40003',
  },
  {
    id: 'emp_004',
    name: 'Rohan Patel',
    email: 'r.patel@company.com',
    phone: '+91 98765 43213',
    role: 'employee',
    department: 'Finance',
    jobTitle: 'Financial Analyst',
    employmentType: 'Full-time',
    status: 'Active',
    joinDate: '2020-06-01',
    salary: 88000,
    address: '22 Navrangpura, Ahmedabad, Gujarat',
    emergencyContact: 'Priya Patel · +91 98765 40004',
  },
  {
    id: 'emp_005',
    name: 'Priya Patel',
    email: 't.kim@company.com',
    phone: '+91 91234 56789',
    role: 'hr',
    department: 'Human Resources',
    jobTitle: 'HR Business Partner',
    employmentType: 'Full-time',
    status: 'Active',
    joinDate: '2021-03-10',
    salary: 80000,
    address: '15 Vastrapur, Ahmedabad, Gujarat',
    emergencyContact: 'Rakesh Patel · +91 98765 40005',
  },
  {
    id: 'emp_006',
    name: 'Arjun Mehta',
    email: 'm.chen@company.com',
    phone: '+91 98765 43215',
    role: 'employee',
    department: 'Engineering',
    jobTitle: 'Backend Engineer',
    employmentType: 'Contract',
    status: 'Active',
    joinDate: '2023-04-01',
    salary: 90000,
    address: '9 Prahlad Nagar, Ahmedabad, Gujarat',
    emergencyContact: 'Kiran Mehta · +91 98765 40006',
  },
  {
    id: 'emp_007',
    name: 'Vikram Singh',
    email: 'a.davis@company.com',
    phone: '+91 98765 43216',
    role: 'employee',
    department: 'Operations',
    jobTitle: 'Operations Lead',
    employmentType: 'Full-time',
    status: 'Active',
    joinDate: '2019-09-12',
    salary: 75000,
    address: '31 Civil Lines, Jaipur, Rajasthan',
    emergencyContact: 'Amit Singh · +91 98765 40007',
  },
  {
    id: 'emp_008',
    name: 'Sneha Nair',
    email: 'q.martinez@company.com',
    phone: '+91 98765 43217',
    role: 'employee',
    department: 'Product',
    jobTitle: 'Product Manager',
    employmentType: 'Full-time',
    status: 'Active',
    joinDate: '2022-02-14',
    salary: 105000,
    address: '27 Marine Drive, Kochi, Kerala',
    emergencyContact: 'Deepak Nair · +91 98765 40008',
  },
  {
    id: 'emp_009',
    name: 'Karan Malhotra',
    email: 'd.thompson@company.com',
    phone: '+91 98765 43218',
    role: 'employee',
    department: 'Legal',
    jobTitle: 'Legal Counsel',
    employmentType: 'Part-time',
    status: 'Active',
    joinDate: '2020-11-30',
    salary: 120000,
    address: '42 Rajouri Garden, New Delhi',
    emergencyContact: 'Pooja Malhotra · +91 98765 40009',
  },
  {
    id: 'emp_010',
    name: 'Aditi Sharma',
    email: 's.brown@company.com',
    phone: '+91 98765 43219',
    role: 'employee',
    department: 'Design',
    jobTitle: 'Graphic Designer',
    employmentType: 'Intern',
    status: 'Active',
    joinDate: '2024-01-08',
    salary: 35000,
    address: '11 Banjara Hills, Hyderabad, Telangana',
    emergencyContact: 'Vivek Sharma · +91 98765 40010',
  },
  {
    id: 'emp_011',
    name: 'Priya Patel',
    email: 'hr@company.com',
    phone: '+91 91234 56789',
    role: 'hr',
    department: 'Human Resources',
    jobTitle: 'HR Director',
    employmentType: 'Full-time',
    status: 'Active',
    joinDate: '2021-03-10',
    salary: 110000,
    address: '20 SG Highway, Ahmedabad, Gujarat',
    emergencyContact: 'Rakesh Patel · +91 98765 40011',
  },
  {
    id: 'emp_012',
    name: 'Aarav Sharma',
    email: 'admin@company.com',
    phone: '+91 98765 43210',
    role: 'admin',
    department: 'Engineering',
    jobTitle: 'CTO',
    employmentType: 'Full-time',
    status: 'Active',
    joinDate: '2020-01-15',
    salary: 150000,
    address: '1 GIFT City, Gandhinagar, Gujarat',
    emergencyContact: 'Meera Sharma · +91 98765 40012',
  },
];

export const EMPLOYEES_STORAGE_KEY = 'employees';
